# Basic
title: ChenTian
subtitle: EL PSY CONGROO.
welcome_message: Welcome to my World
description: 你好，我是 ChenTian，是个程序员。
creator: <a href="http://www.GcsSloop.com">@GcsSloop</a>

#url: "http://www.gcssloop.com"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: #slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: GitHub,     in_site: false,  description: ChenTian's GitHub,    url: 'https://github.com/ChenTianSaber'}
    - {title: 目录,        in_site: true,  description: 博客目录,               url: '/timeline'}
    - {title: 关于,        in_site: true,  description: 关于作者 ChenTian,       url: '/info/about'}
    


gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: ChenTian
    # duoshuo:
# Social
social:
    weibo: ChenTian
    github: ChenTian
    twitter: ChenTian
    rss: /feed.xml
    mail: ChenTianSaber@163.com
    copyright: http://choosealicense.online

# Google Analytics
#ga:
#    id: UA-82493667-1
#    host: www.gcssloop.com
